### ISSUE TITLE
A potential bug in FIFO test:

### ISSUE THREAD

**Issue by ZheWang711** [brandonio21/ucsd-cs120-wi16-pa2-tester#18]
``` C
/* check if all process are exited */
  if (get_next_sched()) {
    Printf("FIFO ERR: Not all processes have exited\n");
    failCounter++;
  }
```

The tester program called "get_next_sched()" to check if all processes have exited, but when the operating system use a FIFO scheduler, the "get_next_sched()" may only be called at the time after a process exit (Since there is no preempt) . Therefore, we might assume that "get_next_sched()" may never be called after all processes exits, which means that we don't need to check if there is no process to exit in the "SchedProc()". If we implement our algorithm in that way, the auto tester may output wrong results like this (all the processes have in fact exited but it says not)!

`FIFO ERR: Not all processes have exited`

**Comment by brandonio21** [comment]
Right. I think the confusion is actually in the error message itself. This is not actually testing whether all processes have exited or not, but rather if the scheduler will attempt to schedule a process that is not valid (ie has already exited).

Therefore, the test is correct if it outputs an error, but the error message is wrong. It should probably read:

```
FIFO ERR: Attempted to schedule a process when no valid process exists
```

**Comment by ZheWang711** [comment]
Yep, that would be helpful.
